### PR TITLE
Added kernel 3.11 support and 1b80:c880 device

### PR DESCRIPTION
**Pull request by daniviga**
Added kernel 3.11 support (Fedora 19) and 1b80:c880 device:

Bus 001 Device 003: ID 1b80:c880 Afatech (found on Asus All-in-one ET2311i)

### CODE REVIEW

**Comment by valtri** [comment]
This breaks 0413:6a03. I think there is a chaos in original code (or at least in the comments), so reshuffling devices is problematic... I'll look at it tomorrow, if you won't do it sooner. ;-)

The "Linux for Workgroups" part (added kernel 3.11 headers) looks OK.

**Comment by daniviga** [comment]
Thanks a lot. No hurries at all. Yes, there is a bit of confusion in the original driver (btw it works! :)). I did it in the night so I can also have a deeper look at it.

Cheers

**Comment by alexmaloteaux** [comment]
Hi Guys 

I ll submit a patch later today with some code reorganisation too regarding the mess in the original driver and all severals patches submitted ... 

however in the meantime maybe you could help:

I have a noxon dab rev1 that works great with your driver; however my twintech ut-40 that is listed too in the driver (1b80:d3a4) and has the same chip (FC0013) does not load. Could you just hint me where i should check in the code for issue. 

my dmesg is : 
[12552.338314] usb 1-3: New USB device found, idVendor=1b80, idProduct=d3a4
[12552.338323] usb 1-3: New USB device strings: Mfr=1, Product=2, SerialNumber=0
[12552.338329] usb 1-3: Product: Rtl2832UDVB
[12552.338335] usb 1-3: Manufacturer: Realtek

then nothing except the remote control part

**Comment by alexmaloteaux** [comment]
nv managed to get ir working by reworking the driver list (i guess)

**Comment by valtri** [comment]
Yes, it looks like we were doing it parallel. ;-) How device 1b80:d3a4 work with the current code?

Daniele, does device 1b80:c880 work OK with the latest code?

**Comment by daniviga** [comment]
I'll let you know asap! (I'm not at home currently)
Thanks!

**Comment by daniviga** [comment]
Dear all, the latest master is working for me (tested on 3.11.4-201.fc19.x86_64). Thanks!

[  316.216097] dvb-usb: found a 'USB DVB-T DEVICE (Afatech)' in warm state.
[  316.216101] dvb-usb: will pass the complete MPEG2 transport stream to the software demuxer.
[  316.217766] DVB: registering new adapter (USB DVB-T DEVICE (Afatech))
[  316.232867] RTL2832U usb_init_bulk_setting : USB2.0 HIGH SPEED (480Mb/s)
[  316.507776] RTL2832U check_tuner_type : FC0013 tuner on board...
[  317.017454] usb 1-1.3: DVB: registering adapter 0 frontend 0 (Realtek DVB-T RTL2832)...
[  317.017554] input: IR-receiver inside an USB DVB receiver as /devices/pci0000:00/0000:00:1a.0/usb1/1-1/1-1.3/input/input13
[  317.019136] dvb-usb: schedule remote query interval to 287 msecs.
[  317.019140] dvb-usb: USB DVB-T DEVICE (Afatech) successfully initialized and connected.
[  317.019160] usbcore: registered new interface driver dvb_usb_rtl2832u

**Pull request closed without merging**
